import type { CSSProperties } from "react";
import { COLORS } from "@/lib/theme";

// Ported verbatim from the design canvas's home-v1.jsx style objects.
export const homeV1Styles: Record<string, CSSProperties> = {
	page: {
		width: "100%",
		maxWidth: 1440,
		margin: "0 auto",
		color: COLORS.ink,
		fontFamily: '"Newsreader", Georgia, serif',
	},

	hero: {
		position: "relative",
		height: 820,
		overflow: "hidden",
		background: COLORS.inkDark,
	},
	heroSlide: {
		position: "absolute",
		inset: 0,
		width: "100%",
		height: "100%",
		objectFit: "cover",
		filter: "contrast(1.02) brightness(0.88)",
		transition: "opacity 1.6s ease-in-out",
	},
	heroScrim: {
		position: "absolute",
		inset: 0,
		background:
			"linear-gradient(180deg, rgba(8,6,4,0.45) 0%, rgba(8,6,4,0) 18%, rgba(8,6,4,0) 55%, rgba(8,6,4,0.55) 100%)",
	},

	hbLinksRow: { display: "flex", alignItems: "center", gap: 14 },
	heroBottomLeft: {
		position: "absolute",
		left: 56,
		bottom: 56,
		color: COLORS.cream,
		display: "flex",
		alignItems: "flex-end",
		gap: 56,
	},
	hbColumn: { display: "flex", flexDirection: "column" },
	hbName: {
		fontFamily: '"Permanent Marker", cursive',
		lineHeight: 0.9,
		margin: 0,
		letterSpacing: "-0.016em",
	},
	hbTag: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 11,
		letterSpacing: "0.22em",
		textTransform: "uppercase",
		fontWeight: 600,
		opacity: 0.8,
		marginTop: 14,
	},
	hbAboutTitle: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 11,
		letterSpacing: "0.24em",
		textTransform: "uppercase",
		fontWeight: 600,
		margin: 0,
		marginBottom: 14,
		color: COLORS.cream,
		opacity: 0.8,
	},

	heroBottomRight: {
		position: "absolute",
		right: 56,
		bottom: 56,
		color: COLORS.cream,
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-end",
		gap: 14,
	},
	hbrKicker: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 13,
		letterSpacing: "0.32em",
		textTransform: "uppercase",
		color: COLORS.cream,
	},
	hbrSocialBtn: {
		width: 32,
		height: 32,
		border: "1px solid rgba(246,244,239,0.85)",
		background: "rgba(8,6,4,0.52)",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		color: COLORS.cream,
		cursor: "pointer",
		transition: "all .15s",
	},
	hbrEnterBtn: {
		display: "inline-flex",
		alignItems: "center",
		gap: 10,
		padding: "10px 18px",
		background: COLORS.cream,
		color: COLORS.ink,
		border: "none",
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 11,
		letterSpacing: "0.18em",
		textTransform: "uppercase",
		fontWeight: 600,
		cursor: "pointer",
		textDecoration: "none",
	},

	heroDots: {
		position: "absolute",
		top: "50%",
		right: 24,
		transform: "translateY(-50%)",
		display: "flex",
		flexDirection: "column",
		gap: 8,
		zIndex: 3,
	},
	heroDot: {
		width: 5,
		height: 5,
		borderRadius: 5,
		background: "rgba(244,236,216,0.35)",
		cursor: "pointer",
		transition: "all .25s",
	},
	heroDotActive: { height: 24, background: COLORS.cream, borderRadius: 3 },

	section: { padding: "56px 56px" },
	sectionHead: {
		display: "flex",
		alignItems: "baseline",
		justifyContent: "space-between",
		paddingBottom: 28,
		borderBottom: "1px solid rgba(26,23,20,0.18)",
		marginBottom: 32,
	},
	sectionTitle: {
		fontFamily: '"Permanent Marker", cursive',
		fontSize: 72,
		margin: 0,
		lineHeight: 0.9,
		letterSpacing: "-0.016em",
	},
	sectionSub: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 11,
		letterSpacing: "0.18em",
		textTransform: "uppercase",
		fontWeight: 600,
		opacity: 0.5,
	},
	filters: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 40 },
	filter: {
		padding: "9px 16px",
		borderRadius: 999,
		border: "1px solid rgba(26,23,20,0.2)",
		cursor: "pointer",
		background: "transparent",
		color: COLORS.ink,
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 11,
		letterSpacing: "0.14em",
		textTransform: "uppercase",
		fontWeight: 600,
	},
	filterActive: {
		background: COLORS.ink,
		color: COLORS.cream,
		border: `1px solid ${COLORS.ink}`,
	},

	card: {
		position: "relative",
		cursor: "pointer",
		overflow: "hidden",
		display: "block",
		textDecoration: "none",
		color: "inherit",
	},
	cardOverlay: {
		position: "absolute",
		inset: 0,
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-end",
		gap: 4,
		padding: "16px",
		background:
			"linear-gradient(to top, rgba(10,8,5,0.78) 0%, rgba(10,8,5,0.35) 55%, transparent 100%)",
		color: COLORS.cream,
	},
	cardOverlayMeta: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 10,
		letterSpacing: "0.16em",
		textTransform: "uppercase",
		fontWeight: 600,
		opacity: 0.75,
	},
	cardOverlaySummary: {
		fontFamily: '"Newsreader", Georgia, serif',
		fontSize: 15,
		lineHeight: 1.5,
		opacity: 0.92,
		maxWidth: "46ch",
	},
	cardTitle: {
		fontFamily: '"Permanent Marker", cursive',
		margin: 0,
		letterSpacing: "-0.01em",
	},

	mobileStack: {
		position: "absolute",
		left: 20,
		right: 20,
		bottom: 24,
		display: "flex",
		flexDirection: "column",
		gap: 10,
		color: COLORS.cream,
	},
	mobileEnter: {
		padding: "18px 20px",
		background: COLORS.creamWarm,
		color: COLORS.ink,
		border: "none",
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 13,
		letterSpacing: "0.18em",
		textTransform: "uppercase",
		fontWeight: 700,
		cursor: "pointer",
		textDecoration: "none",
		display: "block",
		textAlign: "center",
		boxShadow: "0 8px 28px rgba(0,0,0,0.28)",
	},
	mobileLink: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		padding: "16px 18px",
		minHeight: 56,
		border: "1px solid rgba(246,244,239,0.45)",
		color: COLORS.cream,
		textDecoration: "none",
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 12,
		letterSpacing: "0.16em",
		textTransform: "uppercase",
		fontWeight: 600,
		background: "rgba(10,8,5,0.35)",
	},
	mobileLinkLeft: { display: "flex", alignItems: "center", gap: 14 },

	tierHead: {
		display: "flex",
		alignItems: "baseline",
		justifyContent: "space-between",
		margin: "0 0 20px",
		paddingBottom: 10,
		borderBottom: "1px solid rgba(26,23,20,0.14)",
	},
	tierLabel: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 11,
		letterSpacing: "0.24em",
		textTransform: "uppercase",
		opacity: 0.5,
	},
	tierNote: {
		fontFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
		fontSize: 10,
		letterSpacing: "0.18em",
		textTransform: "uppercase",
		fontWeight: 600,
		opacity: 0.4,
	},
	tier1Grid: {
		display: "grid",
		gridTemplateColumns: "repeat(2, minmax(0,1fr))",
		gap: 28,
		marginBottom: 80,
	},
	tier2Grid: {
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0,1fr))",
		gap: 20,
		marginBottom: 80,
	},
	tier3Grid: {
		display: "grid",
		gridTemplateColumns: "repeat(5, minmax(0,1fr))",
		gap: 16,
	},
	empty: { opacity: 0.5, padding: "24px 0" },
};
